"""Add tone and target_length to LinkedInPost

Revision ID: beaa2c989792
Revises: 962de9c9f900
Create Date: 2025-10-21 15:20:44.215378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beaa2c989792'
down_revision: Union[str, Sequence[str], None] = '962de9c9f900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_posts', sa.Column('tone', sa.String(), nullable=True))
    op.add_column('linkedin_posts', sa.Column('target_length', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linkedin_posts', 'target_length')
    op.drop_column('linkedin_posts', 'tone')
    # ### end Alembic commands ###
