"""Add Clerk user fields to user_preferences

Revision ID: c311ff80df94
Revises: 3f0d40cb17e8
Create Date: 2025-10-15 12:08:12.749813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c311ff80df94'
down_revision: Union[str, Sequence[str], None] = '3f0d40cb17e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('clerk_user_id', sa.String(), nullable=False))
    op.add_column('user_preferences', sa.Column('email', sa.String(), nullable=False))
    op.add_column('user_preferences', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('user_preferences', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('user_preferences', sa.Column('username', sa.String(), nullable=True))
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.create_index(op.f('ix_user_preferences_clerk_user_id'), 'user_preferences', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_user_preferences_email'), 'user_preferences', ['email'], unique=True)
    op.create_index(op.f('ix_user_preferences_username'), 'user_preferences', ['username'], unique=True)
    op.drop_column('user_preferences', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_preferences_username'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_email'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_clerk_user_id'), table_name='user_preferences')
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.drop_column('user_preferences', 'username')
    op.drop_column('user_preferences', 'last_name')
    op.drop_column('user_preferences', 'first_name')
    op.drop_column('user_preferences', 'email')
    op.drop_column('user_preferences', 'clerk_user_id')
    # ### end Alembic commands ###
